version: '3'
networks:
  api-network:
    driver: bridge

services:
  detect-cracks-signs:
    stdin_open: true
    tty: true
    build:
      context: ./business_logic
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - api-network
    environment:
      - PORT=5000
      - MERGED_CRACK_DETECTION_URL=http://host.docker.internal:5001/MergedCrackDetection
      - ROAD_CRACK_DETECTION_URL=http://host.docker.internal:5002/RoadCrackDetection
      - ROAD_TRAFFIC_SIGN_DETECTION_URL=http://host.docker.internal:5003/TrafficSignDetection
    restart: always

  detect-building-cracks-api:
    stdin_open: true
    tty: true
    build:
      context: ./merged_crack_detection
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "5001:5001"
    networks:
      - api-network
    environment:
      - PORT=5001
    restart: always

  detect-road-cracks-api:
    stdin_open: true
    tty: true
    build:
      context: ./road_crack_detection
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "5002:5002"
    networks:
      - api-network
    environment:
      - PORT=5002
    restart: always

  detect-road-traffic-signs-api:
    stdin_open: true
    tty: true
    build:
      context: ./road_traffic_sign_detection
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "5003:5003"
    networks:
      - api-network
    environment:
      - PORT=5003
    restart: always


