version: '3'

services:
  road_crack_detection:
    build:
      context: ./road_crack_detection
    ports:
      - "5000:5000"
    restart: always
  
  road_potholes_detection:
    build:
      context: ./road_potholes_detection
    ports:
      - "5001:5001"
    restart: always

  merged_crack_detection:
    build:
      context: ./merged_crack_detection
    ports:
      - "5002:5002"
    restart: always